README.rst
dceu2019/setup.cfg
dceu2019/src/dceu2019/settings/pretalx.py
dceu2019/src/dceu2019/urls.py

This fixes a few issues running PreTalx locally, and adds a missing dependecy prior to deployment in a production env.

Missing pretalx configurations and dependency

---

public_html/index.html

Add a note about the CfP, in case people are wondering if we're alive.

Update about CfP

---

dceu2019/setup.cfg
dceu2019/src/dceu2019/celery_app.py
dceu2019/src/dceu2019/settings/base.py
dceu2019/src/dceu2019/settings/production.py

A bunch of small adjustments done yesterday, trying to get things working.

Pretalx production fixes

---

hugo_site/themes/dceu2019/layouts/partials/header.html

Sorry about all this, but testing in production as we have no current staging server... I suspect that debugging Twitter cards is an edge case for static site generators :)

Fix syntax errors and expand twitter meta data

---

README.rst
hugo_site/config.toml
hugo_site/content/cfp.md
hugo_site/content/conduct.md
hugo_site/themes/dceu2019/static/css/print.css

* Fix printer-friendlyness (hide header/footer)

Various smaller fixes

---

hugo_site/content/conduct.md
hugo_site/themes/dceu2019/static/css/style.css

These are some small updates, just want to make sure they have your attention in case I touched something that was intentional.
CC: @RadicalPet @valberg

Small Code of Conduct updates (only language+syntax, no content)

---

hugo_site/themes/dceu2019/layouts/index.html
hugo_site/themes/dceu2019/layouts/partials/header.html
hugo_site/themes/dceu2019/static/css/style.css

Addresses #37 mobile issues and #38

Update the hugo theme for mobile screens

---

hugo_site/content/tickets.md

Add a text about the Privacy extension blocking

---

hugo_site/content/tickets.md

Not really a "sign up" page per say

Alternative link for ticket purchase

---

hugo_site/content/hospitality.md

Included the hospitality deals.

Hospitality page created

---

hugo_site/content/grants.md

Contents coordinated through the Grants team.

Opportunity Grants page

---

hugo_site/content/_index.html

Fix front page timeline

---

hugo_site/themes/dceu2019/assets/style.scss

Make submenus more profiled and font size match the top menu

---

hugo_site/content/contact.md
hugo_site/content/django-denmark.md
hugo_site/content/team.md

add team/credits page

---

hugo_site/content/_index.html
hugo_site/content/accessibility.md
hugo_site/content/bikes.md
hugo_site/content/contact.md
hugo_site/content/hospitality.md
hugo_site/content/information.md
hugo_site/content/sponsors.md
hugo_site/content/visa.md

Add descriptions to pages that dont have them

---

hugo_site/content/hospitality.md

- Changed hotels/hostels order, from most practical to less practical.
- Added info in introduction paragraph.

Updated content in hospitality.md

---

hugo_site/content/cfp.md
hugo_site/content/grants.md
hugo_site/content/selection-process.md
hugo_site/content/speaker-mentors.md
hugo_site/content/talks.md

Preparing for CfP process and grant window closing

---

hugo_site/themes/dceu2019/assets/style.scss
hugo_site/themes/dceu2019/layouts/partials/nav.html

This solution might solve the submenu problem. Could you please review?

Fixed submenus

---

hugo_site/content/_index.html
hugo_site/content/tickets.md
hugo_site/themes/dceu2019/assets/style.scss
hugo_site/themes/dceu2019/layouts/partials/footer.html

Following has changed here:
1. The newsletter form is removed
1. The ticket purchase area looks nice and clean

Updates: Ticket button and newsletter on front page only

---

hugo_site/content/_index.html

Gonna make a quick call here, please amend afterwards

Update pioneer tickets

---

hugo_site/content/_index.html

Add a general description of the conference to the front page

---

.travis.yml
README.rst
hugo_site/content/sponsors.md

Text updates for the Sponsorship page

---

hugo_site/content/selection-process.md

This makes the page more evident in Twitter previews

Description text for the talk selection page

---

dceu2019/src/dceu2019/apps/invoices/admin.py
dceu2019/src/dceu2019/apps/invoices/management/commands/ticketbutler2billy.py
dceu2019/src/dceu2019/apps/invoices/models.py

Save people's sprints choice from ticket order, so we can get their final answers later! (a lot have selected "Maybe")

Parse sprints preference from Ticketbutler

---

hugo_site/content/cfp.md

fixing typos in sentence about typos

---

dceu2019/src/dceu2019/apps/pretalx_utils/management/commands/pretalx_hugoschedule.py

This way of working is of course only what is realistic to do right now to get the first list confirmed and published :)

Adjust published talks pending an abstract

---

.gitignore
dceu2019/src/dceu2019/apps/pretalx_utils/management/commands/pretalx_hugoschedule.py
hugo_site/content/talks/_index.md
hugo_site/data/talks.json
hugo_site/themes/dceu2019/layouts/news/list.html
hugo_site/themes/dceu2019/layouts/partials/footer.html
hugo_site/themes/dceu2019/layouts/partials/nav.html
hugo_site/themes/dceu2019/layouts/talks/list.html
hugo_site/themes/dceu2019/layouts/talks/single.html

Write talk detail pages from Django management script and link them from talk list

---

dceu2019/setup.cfg
dceu2019/src/dceu2019/apps/invoices/admin.py
dceu2019/src/dceu2019/apps/invoices/management/commands/ticketbutler2billy.py
dceu2019/src/dceu2019/apps/invoices/models.py
dceu2019/src/dceu2019/apps/invoices/templates/invoices/ticket_list.html
dceu2019/src/dceu2019/apps/invoices/views.py
dceu2019/src/dceu2019/apps/ticketholders/views.py
dceu2019/src/dceu2019/settings/base.py
dceu2019/src/dceu2019/urls.py

Adds PDF invoice display for ticketholders

Update Ticketbutler API and data parsing and saving

---

hugo_site/content/accessibility.md

Live Captioning UK  mentioned as the Speech-to-text service provider on the accessibility page

Live Captioning UK link added

---

hugo_site/themes/dceu2019/assets/static/style.scss

Oh wow not sure what happened @sodevious but now it looks okay :)

Fix newsletter form placement

---

dceu2019/src/dceu2019/apps/invoices/management/commands/ticketbutler2billy.py
dceu2019/src/dceu2019/apps/invoices/models.py

Marks people in groups with a ticket active.
Needed of course 2 loops, but had somehow gotten the logic mixed into a single loop.

Fixes a regretful import bug marking users inactive prematurely

---

dceu2019/src/dceu2019/apps/invoices/management/commands/invite_ticketholders.py

Fix lookup error for re-invites

---

dceu2019/src/dceu2019/apps/invoices/management/commands/invite_ticketholders.py

Include everyone who never had an invite dtm stamp

---

dceu2019/src/dceu2019/apps/ticketholders/templates/ticketholders/auth/reinvite_email.txt

Missing blocktrans

---

dceu2019/src/dceu2019/apps/invoices/management/commands/invite_ticketholders.py

Skip already activated users when re-inviting

---

dceu2019/src/dceu2019/apps/invoices/management/commands/invite_ticketholders.py

Use timezone stamps correctly

---

hugo_site/data/sponsors.json
hugo_site/data/sponsors_community.json
hugo_site/themes/dceu2019/assets/static/style.scss
hugo_site/themes/dceu2019/layouts/partials/sponsors.html

Move Django Verein as a community sponsor and align vertically

---

dceu2019/src/dceu2019/apps/ticketholders/templates/ticketholders/bikes/booking.html

Fix awkward text introducing the bike concept

---

dceu2019/src/dceu2019/apps/pretalx_utils/admin.py
dceu2019/src/dceu2019/apps/pretalx_utils/management/commands/pretalx_hugoschedule.py
hugo_site/themes/dceu2019/layouts/partials/footer.html
hugo_site/themes/dceu2019/layouts/talks/single.html

and speaker's twitter accounts in talks

Add our Twitter account to footer

---

hugo_site/content/sprints.md

Should we be adding a timeframe on this? like 9-17 or 10-17?

Sprints page with venue information

---

dceu2019/src/dceu2019/apps/invoices/templates/invoices/ticket_list.html

Un-interable manytomany manager after swapping it out with a related_name

---

hugo_site/content/django-denmark.md

Fix @emilkjer's issue

---

dceu2019/src/dceu2019/apps/ticketholders/management/commands/email_ticketholders.py

Still no test-driven development here :roll_eyes:

Only send to confirmed recipients

---

dceu2019/src/dceu2019/apps/ticketholders/management/commands/email_ticketholders.py

This will help for sending out the next batch of updates :)

Be a bit more verbose about how emails are sent

---

dceu2019/src/dceu2019/apps/ticketholders/admin.py
dceu2019/src/dceu2019/apps/ticketholders/templates/ticketholders/sprints.html

Sprints title confirmed filter

---

dceu2019/src/dceu2019/apps/ticketholders/views.py

Another case of not doing TDD: Added a fix to avoid leaking email subscription state and it was really wrong.

Sort out confirmation conditional

---

hugo_site/content/_index.html

Fix front page update

---

dceu2019/src/dceu2019/apps/invoices/management/commands/ticketbutler2billy.py

Keyword typo fix

---

hugo_site/content/news/sold-out.md
hugo_site/themes/dceu2019/layouts/partials/summary.html

Hi all,
I published this very late last night but found it in bad taste to publish news without including others. So here's a PR :)
Reverts djangocon/2019.djangocon.eu#300

New news story

---

hugo_site/content/live.md
hugo_site/content/schedule.md
hugo_site/content/talks/_index.md

We want to be taking questions from the internet crowd.
RFC: @MarkusH @rixx @freakboy3742 @ericholscher @mxsasha @dawnwages 
Left to do:

Add live stream URL and questions info

---

dceu2019/src/dceu2019/apps/pretalx_utils/management/commands/pretalx_hugoschedule.py
dceu2019/src/dceu2019/apps/ticketholders/templates/ticketholders/workshops.html
hugo_site/themes/dceu2019/layouts/talks/single.html

Timeslots for talk detail pages

---

dceu2019/src/dceu2019/apps/pretalx_utils/management/commands/pretalx_hugoschedule.py

Force localtime in django management command

---

hugo_site/themes/dceu2019/layouts/talks/single.html

Explicit timezone @emilkjer and future continous article/tense @valberg

Updates to display of time and live info

---

dceu2019/src/dceu2019/apps/invoices/management/commands/ticketbutler2billy.py

Fixes `AssertionError: TicketbutlerTicket object can't be deleted because its id attribute is set to None.`

remove ticket only once

---

hugo_site/content/news/videos-and-photos.md

People asked about this, and the twitter announcement isn't really sufficient... will write some more news and send out emails, too.

Add news about photos and videos
